version: '3.3'

services:
  db:
    image: mysql:5.7
    command: --innodb-log-file-size=500M --innodb_strict_mode=0
    restart: "no"
    volumes:
      - ~/softlinks/mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  dev:
    depends_on:
      - db
    image: rapporteket/nra-dev:master
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - ~/GIT/nra:/home/rstudio/nra
      - ~/softlinks/mydata:/home/rstudio/mydata
    ports:
      - "8787:8787"
      - "3838:3838"
    dns:
      - 8.8.8.8
    restart: "no"
    environment:
      PASSWORD: password
      DB_HOST: db
      DB_USER: root
      DB_PASS: root

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
